version: "3.8"

services:
  comfyui:
    build: ./
    image: yuwenbao/runpod-worker-comfy:test 
    container_name: comfyui-worker
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - SERVE_API_LOCALLY=true
    runtime: nvidia
